-- This is just a dumping file for scripts to build the database
--Table structure for table `account`
CREATE TABLE handcrafted.account (
    account_id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_image character varying NOT NULL
);
--Table structure for table `category`
--Use INT instead of UUID since there will probably only be a few categories
CREATE TABLE IF NOT EXISTS handcrafted.category (
    category_id INT GENERATED BY DEFAULT AS IDENTITY,
    category_name character varying NOT NULL,
    CONSTRAINT category_pk PRIMARY KEY (category_id)
);
-- Table structure for table `product`
-- Removed the product_thumbnail property since not part of MVP
CREATE TABLE IF NOT EXISTS handcrafted.product (
    product_id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    product_title character varying NOT NULL,
    product_description TEXT NOT NULL,
    product_image character varying NOT NULL,
    product_price numeric(9, 2) NOT NULL,
    category_id INT NOT NULL,
    artist_id UUID NOT NULL
);
-- Create relationship between `category` and `product` tables
ALTER TABLE IF EXISTS handcrafted.product
ADD CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES handcrafted.category (category_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION;
-- Create relationship between `account` and `product` tables
ALTER TABLE IF EXISTS handcrafted.product
ADD CONSTRAINT fk_account FOREIGN KEY (artist_id) REFERENCES handcrafted.account (account_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION;
-- Data for table `category`
-- Category names generated using ChatGPT
INSERT INTO handcrafted.category (category_name)
VALUES ('Artisanal'),
    ('Textiles and Fabrics'),
    ('Jewerly and Accessories'),
    ('Home Decor and Furnishings'),
    ('Personal Care'),
    ('Stationary and Paper Goods');
-- data for accounts table
-- dummy account
INSERT INTO handcrafted.account (
        account_id,
        account_firstname,
        account_lastname,
        account_email,
        account_password,
        account_image
    )
VALUES (
        '538c6f54-a22a-49a3-8815-8938c2f58932',
        'Leonardo',
        'Da Vinci',
        'leodv@mail.com',
        '123456',
        '/images/users/leonardo.jpg'
    );
-- data for products table
-- dummy product for dummy account
INSERT INTO handcrafted.product (
        product_title,
        product_description,
        product_image,
        product_price,
        category_id,
        artist_id
    )
VALUES (
        'Monalisa',
        'This is the Mona Lisa.',
        '/images/products/mona_lisa.jpg',
        12345.67,
        1,
        '538c6f54-a22a-49a3-8815-8938c2f58932'
    );
-- create table 'rating'
CREATE TABLE IF NOT EXISTS handcrafted.rating (
    rating_id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    rating_title character varying,
    rating_review_text TEXT,
    rating_value INT NOT NULL CHECK (
        rating_value BETWEEN 1 AND 5
    ),
    buyer_id UUID NOT NULL,
    product_id UUID NOT NULL
);
-- create relationship between rating and buyer
ALTER TABLE IF EXISTS handcrafted.rating
ADD CONSTRAINT fk_buyer FOREIGN KEY (buyer_id) REFERENCES handcrafted.account (account_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION;
-- create relationship between rating and product
ALTER TABLE IF EXISTS handcrafted.rating
ADD CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES handcrafted.product (product_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION;
-- create table 'story'
CREATE TABLE IF NOT EXISTS handcrafted.story (
    story_id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    story_content TEXT NOT NULL,
    story_date DATE NOT NULL,
    artist_id UUID NOT NULL
);
-- create relationship between story and artist
ALTER TABLE IF EXISTS handcrafted.story
ADD CONSTRAINT fk_artist FOREIGN KEY (artist_id) REFERENCES handcrafted.account (account_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION;
-- seed users
INSERT INTO handcrafted.account (
        account_id,
        account_firstname,
        account_lastname,
        account_email,
        account_password,
        account_image
    )
VALUES (
        '31a83f3d-1a14-40f9-b7cc-30f9d036f572',
        'Emily',
        'Parker',
        'emily@mail.com',
        'password',
        '/images/users/emily.jpg'
    ),
    (
        'e4cf64e7-b569-4149-8897-df9980266cdd',
        'Anna',
        'Banana',
        'anna@mail.com',
        'password',
        '/images/users/anna.jpg'
    ),
    (
        '1aa97dfd-5aa0-4f80-afce-8cef34880226',
        'Jane',
        'Smith',
        'jane@mail.com',
        'password',
        '/images/users/jane.jpg'
    ),
    (
        'b222d544-c5aa-4558-b4a6-74cd8e088afd',
        'John',
        'Cenamics',
        'john@mail.com',
        'password',
        '/images/users/john.jpg'
    ),
    (
        'cea1b76b-d32d-4afc-939f-e306199c9077',
        'Kit',
        'Kat',
        'kitkat@mail.com',
        'password',
        '/images/users/kit.jpg'
    ),
    (
        'f65944a4-429b-4cfc-904e-26011ceda9e0',
        'Nana',
        'Nah',
        'nananah@mail.com',
        'password',
        '/images/users/nana.jpg'
    ),
    (
        'ad93d122-1058-465e-8720-1ed2f6f8cabb',
        'Rose',
        'Gillian',
        'rose@mail.com',
        'password',
        '/images/users/rose.jpg'
    ),
    (
        'aea73477-ff13-41a1-a86a-5c30859494da',
        'Susan',
        'Davis',
        'susan@mail.com',
        'password',
        '/images/users/susan.jpg'
    );
-- seed emily products
INSERT INTO handcrafted.product (
        product_title,
        product_description,
        product_image,
        product_price,
        category_id,
        artist_id
    )
VALUES (
        'Anne of Green Gables Amigurumi',
        'This handcrafted amigurumi is based on Anne of Green Gables',
        '/images/products/emily_amigurumi_anne.jpg',
        42.50,
        2,
        '31a83f3d-1a14-40f9-b7cc-30f9d036f572'
    ),
    (
        'Dinosaur Amigurumi',
        'Perfect gift for dinosaur lovers!',
        '/images/products/emily_amigurumi_dino.jpg',
        32.50,
        2,
        '31a83f3d-1a14-40f9-b7cc-30f9d036f572'
    ),
    (
        'Woven Basket with Handle',
        'Use this basket for your daily shopping or berry picking.',
        '/images/products/emily_woven_basket.jpg',
        25,
        4,
        '31a83f3d-1a14-40f9-b7cc-30f9d036f572'
    );
-- seed anna products
INSERT INTO handcrafted.product (
        product_title,
        product_description,
        product_image,
        product_price,
        category_id,
        artist_id
    )
VALUES (
        'Blue Cloth Earrings',
        'Up your denim collection with this handcrafted blue denim earrings.',
        '/images/products/anna_blue.jpg',
        12,
        3,
        'e4cf64e7-b569-4149-8897-df9980266cdd'
    ),
    (
        'Peach Clay Earrings',
        'Try something new with this clay earrings with floral design.',
        '/images/products/anna_peach.jpg',
        5.50,
        3,
        'e4cf64e7-b569-4149-8897-df9980266cdd'
    );
-- seed jane products
INSERT INTO handcrafted.product (
        product_title,
        product_description,
        product_image,
        product_price,
        category_id,
        artist_id
    )
VALUES (
        'Green Linen Apron',
        'Protect your clothes with this lovely green linen apron.',
        '/images/products/jane_apron.jpg',
        15,
        2,
        '1aa97dfd-5aa0-4f80-afce-8cef34880226'
    ),
    (
        'Personalized Eco Bag',
        'Print your own design in these canvas bags. Printing service not included.',
        '/images/products/jane_eco_bag.jpg',
        1,
        3,
        '1aa97dfd-5aa0-4f80-afce-8cef34880226'
    ),
    (
        'Hand Painted Sneakers Size 10',
        'Give some color to your outfit with this hand painted sneakers. Comes in Size 10.',
        '/images/products/jane_painted_sneakers.jpg',
        25,
        3,
        '1aa97dfd-5aa0-4f80-afce-8cef34880226'
    ),
    (
        'Lovely Straw Hat with Ribbon',
        'Complete your outdoor look with this classic straw hat with ribbon detail.',
        '/images/products/jane_straw_hat.jpg',
        22,
        3,
        '1aa97dfd-5aa0-4f80-afce-8cef34880226'
    );
-- seed john products
INSERT INTO handcrafted.product (
        product_title,
        product_description,
        product_image,
        product_price,
        category_id,
        artist_id
    )
VALUES (
        'Cracked Bowl with Gold Trim',
        'Elevate your space with this unique ceramic bowl.',
        '/images/products/john_bowl.jpg',
        75,
        4,
        'b222d544-c5aa-4558-b4a6-74cd8e088afd'
    ),
    (
        'Two-Handled Mug',
        'Enjoy a cup of hot drink with this one of a kind double handled creation. Comes in two per set.',
        '/images/products/john_mug.jpg',
        25,
        4,
        'b222d544-c5aa-4558-b4a6-74cd8e088afd'
    ),
    (
        'Dotted Vase',
        'For your flowers, or just for display.',
        '/images/products/john_vase.jpg',
        120,
        4,
        'b222d544-c5aa-4558-b4a6-74cd8e088afd'
    ),
    (
        'White Ceramic Plate with Gold Inlay',
        'Enjoy your food, and enjoy the beauty of this ceramic plate.',
        '/images/products/john_plate.jpg',
        35,
        4,
        'b222d544-c5aa-4558-b4a6-74cd8e088afd'
    );
-- seed kit products
INSERT INTO handcrafted.product (
        product_title,
        product_description,
        product_image,
        product_price,
        category_id,
        artist_id
    )
VALUES (
        'Happy Cat',
        'Yes, it is a sticker.',
        '/images/products/kit_cat.jpg',
        1,
        6,
        'cea1b76b-d32d-4afc-939f-e306199c9077'
    ),
    (
        'Cat Heart',
        'Yes, it is a sticker.',
        '/images/products/kit_cat_heart.jpg',
        1,
        6,
        'cea1b76b-d32d-4afc-939f-e306199c9077'
    ),
    (
        'Cherry',
        'Yes, it is a sticker.',
        '/images/products/kit_cherry.jpg',
        1,
        6,
        'cea1b76b-d32d-4afc-939f-e306199c9077'
    ),
    (
        'Mango',
        'Yes, it is a sticker.',
        '/images/products/kit_mango.jpg',
        1,
        6,
        'cea1b76b-d32d-4afc-939f-e306199c9077'
    ),
    (
        'Peace',
        'Yes, it is a sticker.',
        '/images/products/kit_peace.jpg',
        1,
        6,
        'cea1b76b-d32d-4afc-939f-e306199c9077'
    );
-- seed nana products
INSERT INTO handcrafted.product (
        product_title,
        product_description,
        product_image,
        product_price,
        category_id,
        artist_id
    )
VALUES (
        'Simple Flowers',
        'Yes, it is an embroidery.',
        '/images/products/nana_flowers.jpg',
        50,
        2,
        'f65944a4-429b-4cfc-904e-26011ceda9e0'
    ),
    (
        'Woven Fabric with Pattern',
        'Yes, it is a fabric.',
        '/images/products/nana_pattern_fabric.jpg',
        145,
        2,
        'f65944a4-429b-4cfc-904e-26011ceda9e0'
    ),
    (
        'Red Flower',
        'Yes, it is an embroidery.',
        '/images/products/nana_red_flower.jpg',
        80,
        2,
        'f65944a4-429b-4cfc-904e-26011ceda9e0'
    );
-- seed rose products
INSERT INTO handcrafted.product (
        product_title,
        product_description,
        product_image,
        product_price,
        category_id,
        artist_id
    )
VALUES (
        'Rose Candle',
        'Relax with this rose-scented candle.',
        '/images/products/rose_candle.jpg',
        20,
        5,
        'ad93d122-1058-465e-8720-1ed2f6f8cabb'
    ),
    (
        'Lemon Fragrance',
        'Yes, it is a cream.',
        '/images/products/rose_fragrance.jpg',
        60,
        5,
        'ad93d122-1058-465e-8720-1ed2f6f8cabb'
    );
-- seed susan products
INSERT INTO handcrafted.product (
        product_title,
        product_description,
        product_image,
        product_price,
        category_id,
        artist_id
    )
VALUES (
        'Embossed Handmade Soap',
        'Relax with this embossed handmade soap.',
        '/images/products/susan_embossed.jpg',
        20,
        5,
        'aea73477-ff13-41a1-a86a-5c30859494da'
    ),
    (
        'Marbled Soap',
        'Yes, it is a soap.',
        '/images/products/susan_marbles.jpg',
        30,
        5,
        'aea73477-ff13-41a1-a86a-5c30859494da'
    ),
    (
        'Square Handmade Soap',
        'Yes, it is a soap.',
        '/images/products/susan_squares.jpg',
        15,
        5,
        'aea73477-ff13-41a1-a86a-5c30859494da'
    );
-- add product for leonardo
INSERT INTO handcrafted.product (
        product_title,
        product_description,
        product_image,
        product_price,
        category_id,
        artist_id
    )
VALUES (
        'The Last Supper',
        'Hang it in your kitchen because, why not?',
        '/images/products/last_supper.jpg',
        60000,
        1,
        '538c6f54-a22a-49a3-8815-8938c2f58932'
    );

--ALTER account table
ALTER TABLE handcrafted.account
ADD account_description TEXT DEFAULT 'This user cannot be bothered to add a description.';

-- alter account table to default password to 'password'
ALTER TABLE handcrafted.account
ALTER COLUMN account_password SET DEFAULT 'password';

-- alter account image to default no image
ALTER TABLE handcrafted.account
ALTER COLUMN account_image SET DEFAULT '/images/users/no-image.jpg';

-- INSERT additional non-authenticated users
INSERT INTO handcrafted.account (
	account_firstname,
	account_lastname,
	account_email,
	account_description
)
VALUES
('Emily', 'Johnson', 'emilyjohnson@example.com', 'Passionate about photography and exploring new places. Always seeking beauty in the world.'),
('Michael', 'Rodriguez', 'michael.rodriguez@example.com', 'Tech entusiast, avid gamer, and aspiring coder. Constantly learning and adapting to new technologies.'),
('Sarah', 'Patel', 'sarah.patel@example.com', 'Fitness freak, health advocate, and nature lover. Finding balance between work and wellness.'),
('Daniel', 'Smith', 'daniel.smith@example.com', 'Musician by heart, traveler by soul. Dreaming big and embracing the rhythm of life.'),
('Jessica', 'Brown', 'jessica.brown@example.com', 'Foodie, bookworm, and occasional writer. Believer in the power of words and flavors to unite people.'),
('Ryan', 'Lee', 'ryan.lee@example.com', 'Adventure seeker, adrenaline junkie, and thrill enthusiast. Life is too short for regrets.'),
('Amanda', 'Garcia', 'amanda.garcia@example.com','Dreamer, traveler, and aspiring entrepreneur. Building castles in the air and laying foundations under them.'),
('Christopher', 'Martinez', 'christopher.martinez@example.com', 'Movie buff, pop culture aficionado, and trivia master. Living life one frame at a time.'),
('Lauren', 'Scott', 'lauren.scott@example.com', 'Animal lover, volunteer, and advocate for a greener planet. Making a difference, one paw print at a time.'),
('Tyler', 'White', 'tyler.white@example.com', 'Sports enthusiast, fitness fanatic, and outdoor adventurer. Chasing goals and breaking personal records.');

-- INSERT reviews and ratings
-- IMPORTANT!!! CHANGE THE UUIDs if during account and product creation, you generated different ones.
INSERT INTO handcrafted.rating (rating_title, rating_review_text, rating_value, buyer_id, product_id)
VALUES
('Great product!', 'I am very satisfied with my purchase. It exceeded my expectations.', 5, '4d9c5baa-b320-4476-b6eb-8e5ba078426c', 'efa2713a-6c72-4ad4-9c1b-25c9466397a5'),
('Good value for money', 'The product is of good quality and the price is reasonable.', 4, 'a248cae4-037d-4572-ac46-6644cfb19037', 'efa2713a-6c72-4ad4-9c1b-25c9466397a5'),
('Could be better', 'I expected better quality for the price I paid.', 3, '6eb8ae1f-b044-41e2-8764-d6dcb6474df0', 'efa2713a-6c72-4ad4-9c1b-25c9466397a5'),
('Disappointed', 'The product did not meet my expectations. It arrived damaged.', 2, 'bca31322-d212-46ae-894d-3a5ab9c3fb90', '7aa9a860-af04-45aa-9103-e36bcf1a773e'),
('Not recommended', 'I regret buying this product. It broke after a few uses.', 1, 'af7d19e3-8e9d-4a5f-b776-936d3ff81519', '7aa9a860-af04-45aa-9103-e36bcf1a773e'),
('Satisfied', 'The product met my expectations. Good quality.', 4, '1bd11b97-f88b-4a2f-8bf1-fa79702a8425', '7aa9a860-af04-45aa-9103-e36bcf1a773e'),
('Excellent service', 'The seller provided excellent customer service. Very responsive and helpful.', 5, '3f9e5089-91cb-4d1f-96a7-2628831bc7c1', '7a02b748-20b5-49c3-aa60-4e6a8accc212'),
('Average product', 'The product is okay, but nothing special.', 3, 'af7d19e3-8e9d-4a5f-b776-936d3ff81519', '7a02b748-20b5-49c3-aa60-4e6a8accc212'),
('Could be improved', 'The product has potential, but there are some flaws that need to be addressed.', 2, 'af7d19e3-8e9d-4a5f-b776-936d3ff81519', '634088e8-1364-4d89-85b3-c64d4edfdbd2'),
('Very disappointed', 'I am extremely disappointed with the product. It broke immediately after use.', 1, '1bd11b97-f88b-4a2f-8bf1-fa79702a8425', '634088e8-1364-4d89-85b3-c64d4edfdbd2'),
('Impressed', 'The product exceeded my expectations. It is of excellent quality.', 5, '3f9e5089-91cb-4d1f-96a7-2628831bc7c1', 'fb34d858-cc8c-4cd8-986d-761efcac119b'),
('Decent product', 'The product is decent for the price. Not exceptional, but does the job.', 3, '3fad172d-38df-4877-93e5-f7d51c250484', 'fb34d858-cc8c-4cd8-986d-761efcac119b'),
('Mixed feelings', 'The product has its pros and cons. Not sure if I would recommend it.', 3, '025a136d-1dd6-4500-a771-c04671c1ee05', 'fb34d858-cc8c-4cd8-986d-761efcac119b'),
('Overpriced', 'I feel like I paid too much for this product. It should be cheaper for what it offers.', 2, 'be6c11c3-629b-496b-87fc-2b8d8173f99f', '2207c6a5-934e-4358-a8ea-bf8f7b04231d'),
('Great value', 'The product offers great value for the price. I am very satisfied.', 5, '4d9c5baa-b320-4476-b6eb-8e5ba078426c', '2207c6a5-934e-4358-a8ea-bf8f7b04231d'),
('Not bad', 'The product is okay. It is not the best, but it gets the job done.', 3, 'a248cae4-037d-4572-ac46-6644cfb19037', '2207c6a5-934e-4358-a8ea-bf8f7b04231d'),
('Poor quality', 'I am very disappointed with the quality of this product. It broke easily.', 1, '6eb8ae1f-b044-41e2-8764-d6dcb6474df0', '5d6ccb7f-60f9-4f1a-a4b2-bfb5905359e6'),
('Highly recommended', 'I highly recommend this product. It is worth every penny.', 5, '6d77c083-c666-4e67-9b5d-db1b999a878d', '5d6ccb7f-60f9-4f1a-a4b2-bfb5905359e6'),
('Good product', 'The product is good overall. I am satisfied with my purchase.', 4, 'bca31322-d212-46ae-894d-3a5ab9c3fb90', '5d6ccb7f-60f9-4f1a-a4b2-bfb5905359e6'),
('Room for improvement', 'The product is decent, but there is definitely room for improvement.', 3, 'af7d19e3-8e9d-4a5f-b776-936d3ff81519', '7a02b748-20b5-49c3-aa60-4e6a8accc212'),
('Exceptional quality', 'I am impressed by the quality of this product. It exceeded my expectations.', 5, '1bd11b97-f88b-4a2f-8bf1-fa79702a8425', '7a02b748-20b5-49c3-aa60-4e6a8accc212');

-- Adding timestamp to rating
ALTER TABLE handcrafted.rating
ADD rating_timestamp TIMESTAMP NOT NULL DEFAULT '2020-01-01 00:00:00';