-- This is just a dumping file for scripts to build the database

--Table structure for table `account`
CREATE TABLE handcrafted.account (
	account_id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
	account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL
);

--Table structure for table `category`
--Use INT instead of UUID since there will probably only be a few categories
CREATE TABLE IF NOT EXISTS handcrafted.category (
	category_id INT GENERATED BY DEFAULT AS IDENTITY,
	category_name character varying NOT NULL,
    CONSTRAINT category_pk PRIMARY KEY (category_id)
);